# Welcome to numpy tutorial

In [1]:
import numpy as np


# Trying Basic Level list with numpy


In [2]:
myarr=np.array([2,3,4,5],np.int64)

In [3]:
myarr[0]

2

In [4]:
myarr.shape

(4,)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0]=45

In [7]:
myarr

array([45,  3,  4,  5], dtype=int64)

# Array Creation : Conversion from other Python structures


In [8]:
arr=np.array([[2,3,4],[3,4,5],[5,6,7]])

In [9]:
arr

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7]])

In [10]:
arr.shape

(3, 3)

In [11]:
arr.size

9

In [12]:
arr.dtype

dtype('int32')

# Instrinsic numpy array creation objects

In [13]:
zeros=np.zeros((3,4))

In [14]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
zeros.dtype


dtype('float64')

In [16]:
zeros.shape

(3, 4)

**Arranging**

In [17]:
range=np.arange(15)

In [18]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Empty Array**

In [19]:
emp=np.empty((4,5))

In [20]:
emp

array([[1.21828587e-311, 6.02760088e-322, 0.00000000e+000,
        0.00000000e+000, 8.45593933e-307],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 1.28822630e-057],
       [6.01347176e-154, 1.28822658e-057, 1.81148490e-152,
        1.13281333e-051, 5.56658500e+141],
       [3.77778426e+180, 1.15998412e-028, 8.93168690e+271,
        4.98131536e+151, 1.94920670e-153]])

In [21]:
emp_like=np.empty_like(arr)

In [22]:
emp_like

array([[4128860, 6029375, 3801155],
       [5570652, 6619251, 7536754],
       [4980828, 7209061, 7733359]])

**Arranging and Shaping**

In [23]:
new_arr=np.arange(99)


In [24]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
new_arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
new_arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

**Axis**

In [27]:
arr

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7]])

In [28]:
arr.sum(axis=0)

array([10, 13, 16])

In [29]:
arr.sum(axis=1)

array([ 9, 12, 18])

In [30]:
arr.T

array([[2, 3, 5],
       [3, 4, 6],
       [4, 5, 7]])

*T* transpose the array.

**1D array**

In [31]:
one=np.array([1,2,3,4,5,656,343])

In [32]:
one

array([  1,   2,   3,   4,   5, 656, 343])

In [33]:
one.argmax()

5

*argmax()* shows the index position of greatest value in an array. 

In [34]:
one.argmin()

0

*argmin()* shows the index position of smallest value in an array.

In [35]:
one.argsort()

array([0, 1, 2, 3, 4, 6, 5], dtype=int64)

*argsort()* displays the index position of values in terms of their size

In [36]:
arr

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7]])

In [38]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [40]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

# Basic array arithmetic operations

In [43]:
arr2=np.array([[2,5,7],[3,7,1],[6,3,8]])

In [44]:
arr2

array([[2, 5, 7],
       [3, 7, 1],
       [6, 3, 8]])

In [46]:
arr

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7]])

In [47]:
arr2 + arr

array([[ 4,  8, 11],
       [ 6, 11,  6],
       [11,  9, 15]])

In [48]:
arr2 - arr

array([[ 0,  2,  3],
       [ 0,  3, -4],
       [ 1, -3,  1]])

In [49]:
arr2 * arr

array([[ 4, 15, 28],
       [ 9, 28,  5],
       [30, 18, 56]])

In [50]:
arr2 / arr

array([[1.        , 1.66666667, 1.75      ],
       [1.        , 1.75      , 0.2       ],
       [1.2       , 0.5       , 1.14285714]])

In [53]:
x=np.sqrt(9)

In [54]:
x

3.0